# Generated by Django 6.0.6 on 2026-06-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default='Unknown', max_length=255)),
                ('candidate_email', models.CharField(default='Not Found', max_length=255)),
                ('candidate_phone', models.CharField(default='Not Found', max_length=100)),
                ('resume_skills', models.JSONField(default=list)),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('skills_by_category', models.JSONField(default=dict)),
                ('skill_coverage', models.FloatField(default=0.0)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('predicted_role', models.CharField(default='Unknown', max_length=100)),
                ('role_probabilities', models.JSONField(default=dict)),
                ('ai_feedback', models.JSONField(default=dict)),
                ('job_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
